### GET request to example server
GET http://localhost:8080/book/find?id=1

### Send POST request with json body
POST https://examples.http-client.intellij.net/post
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}